version: '3'
services:
  restaurants:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1079
  auth:
    image: postgres:15
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1079
  orders:
    image: postgres:15
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1079
  payment:
    image: postgres:15
    ports:
      - 6543:6543
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1079
  restSelection:
    image: postgres:15
    ports:
      - 8008:8008
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1079


